name: build

on: [push, pull_request]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Setup dependencies
        run: npm i
      - name: Build project
        run: npm run build --if-present
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: |
            node_modules
            dist
            package-lock.json
            package.json
            LICENSE
          if-no-files-found: error